import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import { url, api, allData } from '../data/data';
import { IPark,IData } from '../data/types';
import { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import { InputSearch } from '../recoil/atom';

interface IResponse{
  total: string;
  limit: string;
  start: string;
  data:[]
}

function Home(props:any) {
  const[datas,setDatas]:any=useState([])
  const api = process.env.NEXT_PUBLIC_API_KEY;
  const stateName = useRecoilState(InputSearch);
  let count = 10;
  let limits = 0;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="z-[-1]">
        <Navbar />
        <Hero  />
      </main>

      <footer></footer>
    </div>
  );
};
export default Home


